base_url = "https://puppy-witch.github.io"
title = "Puppy-Witches Website"
description = "My personal website, blog, etc"
output_dir = "docs"

theme = "tlachtga"

taxonomies = [
    {name = "tags", feed = true},
    {name = "categories", feed = true},
]
compile_sass = true
build_search_index = true
generate_feeds = true
minify_html = true
default_language = "en"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[search]
include_title = true
include_description = true
include_content = true


[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[extra]
author = "M"
github = "puppy-witch"
pronouns = "She/They/It"

default_theme = "dark"
theme_switcher = true
retro_animations = true
terminal_font = false
accessibility_mode = true
respect_reduced_motion = true

estimated_read_time = true
show_author = true
show_categories = true
show_related_posts = true
enable_comments = false

social_links = [
    {name = "GitHub", url = "https://github.com/puppy-witch", icon = "github"},
    {name = "Matrix", url = "@puppy-witch:matrix.org", icon = "matrix"},
]

menu = [
    {name = "Home", url = "/"},
    {name = "About", url = "/about/"},
    {name = "Blog", url = "/blog/"},
    {name = "Projects", url = "/projects/"},
    {name = "Tags", url = "/tags/"},
]

footer_links = [
    {name = "Anti-Capitalist License", url = "/license/"},
    {name = "Accessibility", url = "/accessibility/"},
    {name = "Source Code", url = "https://github.com/puppy-witch/puppy-witch.github.io"},
]
